---
#- name:          Check if IBM Sterling B2B is already up and running
#  shell:         "ps -ef | grep cdpmgr | grep -v grep"
#  changed_when:  true
#  register:      __cd_running
#  ignore_errors: true

- name:          Is run.sh available?
  stat:
    path:        "{{ __si_install_path }}/bin/run.sh"
  register:      __cmd_installed

- name: Copy password in files to avoid interactive imput
  ansible.builtin.lineinfile:
    line: "passphrase={{ __si_passphrase }}"
    path: "{{ item }}"
    state: present
  loop: 
    - "{{ __si_install_path }}/properties/security.properties"
    - "{{ __si_install_path }}/properties/security.properties.in"

- name:          Start IBM Sterling B2B
  shell: "{{ __si_install_path }}/bin/run.sh"
  args:
    chdir: "{{ __si_install_path }}/bin"
  environment:
    LANG:        "en_US"
  register:      cout
  when:          __cmd_installed.stat.exists

- name: Status
  debug:
    msg: "{{ cout.stdout}}"
    
#- name:          "Start IBM Connect:Direct"
#  become_user:   "{{ __cd_user }}"
#  #environment:
#  #  NDMAPICFG:   "{{ __cd_install_path }}/ndm/cfg/cliapi/ndmapi.cfg""
#  #  PATH:        ""
#  shell:         "{{ __cd_install_path }}/ndm/bin/cdpmgr -i {{ __cd_install_path }}/ndm/cfg/__cd_nodename/initparm.cfg"
#  register:      cout
#  changed_when:  cout.rc == 0
#  when:          __cd_running.rc == 0
