FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV APP_USER=sterling \
    APP_UID=1011 \
    HOME=/home/sterling \
    PLAYBOOK_HOME=/home/sterling/ansible-ibm-sterling \
    HELM_VERSION=v3.15.4 \
    OC_VERSION=4.16

# Install system packages, Python, Ansible
RUN microdnf update -y && \
    microdnf install -y \
        python3 \
        python3-pip \
        python3-setuptools \
        ansible-core \
        git \
        tar \
        gzip \
        unzip \
        curl \
        wget \
        openssh-clients \
        which \
        shadow-utils && \
    microdnf clean all

# Install Helm
RUN curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
        -o /tmp/helm.tar.gz && \
    tar -xzf /tmp/helm.tar.gz -C /tmp && \
    mv /tmp/linux-amd64/helm /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm && \
    rm -rf /tmp/helm.tar.gz /tmp/linux-amd64

# Install OpenShift oc client
RUN curl -sSL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OC_VERSION}/openshift-client-linux-${OC_VERSION}.tar.gz \
        -o /tmp/oc.tar.gz && \
    tar -xzf /tmp/oc.tar.gz -C /tmp && \
    mv /tmp/oc /usr/local/bin/oc && \
    mv /tmp/kubectl /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/oc /usr/local/bin/kubectl && \
    rm -rf /tmp/oc.tar.gz

# Create user "sterling" with UID 1011
RUN useradd -u ${APP_UID} -m -s /bin/bash ${APP_USER}

# Clone the Ansible Sterling playbooks
USER ${APP_UID}
RUN git clone https://github.com/ibm-sterling-devops/ansible-ibm-sterling.git ${PLAYBOOK_HOME}

# Default workdir and entrypoint
WORKDIR /home/sterling
CMD ["/bin/bash"]
