---
# Setup Db2 Server
# 
# ansible-playbook -i environments/hosts.dev -u root playbooks/setup-db2.yml 
#
# CC1U0ML - IBM Db2 Server 11.5 for Linux on AMD64 and Intel EM64T systems (x64) Multilingual
- hosts:                    db2_servers
  become:                   true
  any_errors_fatal:         true
  vars:
    # Application Dependencies
    db2_repository_url: http://9.30.87.162
    db2_package_name: DB2_Svr_10.5.0.3_Linux_x86-64.tar
    db2_version: V11.5
    db2_extraction_subfolder: server
  roles:
    - roles/ibm/db2/db2-install
    - roles/ibm/db2/create-sb2b-db
