---
# Setup Db2 Server
# 
# ansible-playbook -i environments/hosts.dev playbooks/setup-db2.yml 
#
- hosts:                    db2_servers
  become:                   true
  any_errors_fatal:         true

  roles:
    - roles/ibm/db2/db2-install
    - roles/ibm/db2/create-sb2b-db
